### ISSUE TITLE
How to choose release build?

### ISSUE THREAD

**Issue by gasacchi** [Kethku/neovide#437]
Hi, i try to build from source, but due openssl dependencies error. i want to use stable release which one should i choose?
Currently running void linux, thanks :smile:

**Comment by Kethku** [comment]
I recommend using the release in the releases list. If you're feeling spicy you can try running a release from the most recent main branch build here: https://github.com/Kethku/neovide/actions but theres a fair bit of churn (especially right now)

**Comment by Kethku** [comment]
It should be working relatively well if you don't enable multigrid though in the main branch

**Comment by gasacchi** [comment]
i download neovide from release, and try to run it got nothing:
```
chmod +x ./neovide
./neovide

zsh: command not found: neovide
```
is there any dependencies to install first?

**Comment by Kethku** [comment]
hmmm... I'm not super familiar with linux... Looks like our linux build is building on ubuntu. THe instructions for it are here: https://github.com/Kethku/neovide/blob/main/.github/workflows/build.yml#L88-L123

I don't know if this build would suffice for your use cases? Maybe you need a different kind of build? I'm sure we could add another type of build if it can be cross built on ubuntu?

**Comment by gasacchi** [comment]
well, i did try build with cargo earlier but got error while some dependencies require openssl, i using void linux that use libressl by default. i've read issues with build with void and seems issues was closed.

**Comment by gasacchi** [comment]
try looking at skia-rs github repo, someone suggesting install libcurl-devel and i try build again with --release or with  --target=x86_64-unknown-linux-musl still can't build skia-bindings
```
error: failed to run custom build command for `skia-bindings v0.32.1`

Caused by:
  process didn't exit successfully: `/home/gasacchi/xxx/.dev/clone/neovide/target/release/build/skia-bindings-9eeb30d52802e4e0/build-script-build` (signal: 11, SIGSEGV: invalid memory reference)

```

**Comment by Kethku** [comment]
Hmmm. Do you get the same issue when building the skia-safe examples https://github.com/rust-skia/rust-skia#example-applications? If so I might make an issue there.

**Comment by Kethku** [comment]
I think this has been fixed in main. Please reopen if you come back to this and the issue remains.
