### ISSUE TITLE
Fontconfig error: Cannot load default config file

### ISSUE THREAD

**Issue by teto** [Kethku/neovide#465]
I wanted to tackle this issue https://github.com/neovim/neovim/issues/13416 but on my system (nixos) I get
```
Fontconfig warning: line 5: unknown element "description"
Fontconfig error: line 5: invalid attribute 'domain'
Fontconfig warning: "/etc/fonts/conf.d/10-hinting-slight.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/20-unhint-small-vera.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/30-metric-aliases.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/40-nonlatin.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/45-generic.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/45-latin.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/49-sansserif.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/50-user.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/51-local.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/60-generic.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/60-latin.conf", line 4: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/65-nonlatin.conf", line 4: unknown element "description"
Fontconfig error: Cannot load default config file
thread 'main' panicked at 'fonts exist: NotFound', src/renderer/fonts/font_loader.rs:96:57
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
according to https://github.com/NixOS/nixpkgs/issues/94073#issuecomment-668722514 the problem doesn't lie in the above errors but in incompatibilites between fontconfig versions: my nixos font cache uses a more recent version ( 2.13.92) than whatever neovide supports. I am not 100% sure but that's my current guess at the problem. I dont know rust (willing to learn)  but if you could share a patch or a workaround that would be very welcome.

NB: nix files I've been using https://github.com/teto/home/blob/master/nixpkgs/overlays/pkgs/neovide with https://github.com/teto/neovide/tree/nix

**Comment by teto** [comment]
for posterity: I managed to fix the error somehow (added fontconfig to buildInputs + regenerated fontcache for older versions of fontconfig as advised in the previous link). Now I hit https://github.com/Kethku/neovide/issues/459

**Comment by Kethku** [comment]
I just pushed a change which may fix #459 but I'm not sure. Could you give it a try again? I'm super interested in getting the tabline issue fixed as I run into it constantly, but I have zero c++ experience so I've shied away from digging in and fixing it myself.

**Comment by teto** [comment]
yes I would very much like to fix this by 0.5 (and other multigrid issues). I've tried the new commit but didn't change a thing for me.

**Comment by Kethku** [comment]
Ok. I'm going to tinker around with an opengl version of neovide to see if that unblocks your investigation. I'm highly motivated if it means the rough edges on multigrid gets smoothed over

**Comment by Kethku** [comment]
@teto I just pushed an opengl branch which renders (it has a bunch of other issues) and reproduces https://github.com/neovim/neovim/issues/13416. Resizing the window is broken and animations don't work, on top of the other existing winit build issues, but I think it should unblock your investigation. Would you be willing to try it?

There may be some problems with getting skia-safe to build because I'm using some features of the library I haven't used yet, but I think https://github.com/rust-skia/rust-skia/pull/435 says that it should be supported on x11 and wayland. I added the X11 feature to skia-safe so maybe that should allow it to work?

**Comment by teto** [comment]
it has some issues building skia-bindings. Probably a missing library but I dont know what file it is looking for.
```
cargo build
   Compiling skia-bindings v0.37.0
error: failed to run custom build command for `skia-bindings v0.37.0`

Caused by:
  process didn't exit successfully: `/home/teto/neovide/target/debug/build/skia-bindings-ff302e2a543078d3/build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-env-changed=SKIA_DEBUG
  HOST: x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=OPT_LEVEL
  cargo:rerun-if-env-changed=CC
  cargo:rerun-if-env-changed=CXX
  cargo:rerun-if-env-changed=SKIA_OFFLINE_SOURCE_DIR
  cargo:rerun-if-env-changed=FORCE_SKIA_BUILD
  cargo:rerun-if-env-changed=FORCE_SKIA_BINARIES_DOWNLOAD
  TRYING TO DOWNLOAD AND INSTALL SKIA BINARIES: 0.37.0/4a32db33df29d4c98987-x86_64-unknown-linux-gnu-gl-x11
  cargo:rerun-if-env-changed=SKIA_BINARIES_URL
    FROM: https://github.com/rust-skia/skia-binaries/releases/download/0.37.0/skia-binaries-4a32db33df29d4c98987-x86_64-unknown-linux-gnu-gl-x11.tar.gz
  UNPACKING ARCHIVE INTO: /home/teto/neovide/target/debug/build/skia-bindings-87efed1404cd1f47/out/skia
  DOWNLOAD AND INSTALL FAILED: failed to iterate over archive
  STARTING A FULL BUILD
  cargo:rerun-if-env-changed=SDKROOT
  Probing 'python'
  Python 2 found: "python"
  Synchronizing Skia dependencies
  Skipping "../src".
  skia/third_party/externals/d3d12a... @ 169895d529dfce00390a20e69c2f516066fe7a3b
  skia/third_party/externals/expat     @ e976867fb57a0cd87e3b0fe05d59e0ed63c6febb
  skia/third_party/externals/libjpe... @ 64fc43d52351ed52143208ce6a656c03db56462b
  skia/third_party/externals/freetype  @ 40c5681ab92e7db1298273ccf3c816e6a1498260
  skia/third_party/externals/libgif... @ d06d2a6d42baf6c0c91cacc28df2542a911d05fe
  skia/third_party/externals/libwebp   @ 55a080e50af655d1fbe0a5c22954835cdd59ff92
  skia/third_party/externals/harfbuzz  @ 3a74ee528255cc027d84b204a87b5c25e47bff79
  skia/third_party/externals/libpng    @ 386707c6d19b974ca2e3db7f5c61873813c6fe44
  skia/third_party/externals/zlib      @ eaf99a4e2009b0e5759e6070ad1760ac1dd75461
  skia/third_party/externals/piex      @ bb217acdca1cc0c16b704669dd6f91a1b509c406
  skia/third_party/externals/spirv-... @ bdbef7b1f3982fe99a62d076043036abe6dd6d80
  skia/third_party/externals/icu       @ dbd3825b31041d782c5b504c59dcfb5ac7dda08c
  Skia args: is_official_build=true is_debug=false skia_enable_gpu=true skia_use_gl=true skia_use_egl=false skia_use_x11=true skia_use_system_libjpeg_turbo=false skia_use_system_libpng=false skia_use_libwebp_encode=false skia_use_libwebp_decode=false skia_use_system_zlib=false skia_use_xps=false skia_use_dng_sdk=false cc="gcc" cxx="g++" skia_use_icu=false target_os="linux" target_cpu="x86_64" skia_use_expat=true skia_use_system_expat=false extra_cflags=["--target=x86_64-unknown-linux-gnu","-O0"] extra_asmflags=["--target=x86_64-unknown-linux-gnu"]

  --- stderr
  thread 'main' panicked at 'gn error: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /home/teto/.cargo/registry/src/github.com-1ecc6299db9ec823/skia-bindings-0.37.0/build_support/skia.rs:676:10
  stack backtrace:
     0:     0x56175d7be93c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::haee811f030343ff1
     1:     0x56175d7e446f - core::fmt::write::h7db28da9f3cc3c42
     2:     0x56175d7b84f5 - std::io::Write::write_fmt::h1b25d758ec27b86f
     3:     0x56175d79f1f5 - std::panicking::default_hook::{{closure}}::h3cbc53da4ae5ec55
     4:     0x56175d79eef3 - std::panicking::default_hook::h6f6f96fba09cad38
     5:     0x56175d79f84f - std::panicking::rust_panic_with_hook::h2b77a9d9f31f50a0
     6:     0x56175d7bedf7 - std::panicking::begin_panic_handler::{{closure}}::he7089cab3285baf3
     7:     0x56175d7bea7c - std::sys_common::backtrace::__rust_end_short_backtrace::h5b2b5f10870a3b6b
     8:     0x56175d79f3f2 - rust_begin_unwind
     9:     0x56175d7e1b61 - core::panicking::panic_fmt::h010f74ce205c2e26
    10:     0x56175d7ec9f3 - core::result::unwrap_failed::h21666bbf7d40cd85
    11:     0x56175cdd3de4 - core::result::Result<T,E>::expect::hb2eddd8f0de1f350
                                 at /build/rustc-1.49.0-src/library/core/src/result.rs:933:23
    12:     0x56175cdcaca8 - build_script_build::build_support::skia::configure_skia::h056f3867af25e83c
                                 at /home/teto/.cargo/registry/src/github.com-1ecc6299db9ec823/skia-bindings-0.37.0/build_support/skia.rs:664:18
    13:     0x56175cdc9fea - build_script_build::build_support::skia::build::hc424284c62dc6e88
                                 at /home/teto/.cargo/registry/src/github.com-1ecc6299db9ec823/skia-bindings-0.37.0/build_support/skia.rs:596:5
    14:     0x56175cdeda5b - build_script_build::main::h99f8a4d2ca4af717

  ```
  
NB:  Also I noticed I had some githooks running ? is it new or ? i maintain my own branch and it is a bit annoying to have cargo run on every commit.

**Comment by Kethku** [comment]
Re git hooks. If you add -n to your git command it bypasses the githook. I agree its annoying to run cargo every time. I think one of the contributors added it, and I may revisit that decision at some point.

Re build. Interesting. Looks like there aren't prebuilt binaries with both gl and x11. I will push a change which removes the x11 feature and that should unblock that particular issue. Give me a bit.

**Comment by Kethku** [comment]
Ok I've pushed the change which removes the x11 feature from skia-safe. Could you try building again?

Its very possible that this will prevent actually running as it will be missing the x11 support, but at least we should be able to get something building.

**Comment by teto** [comment]
Do you know how libGL detection is implemented ? I've added them in the build environment but paths are non standard on nixos so maybe that confuses the lib.
```
    Finished dev [unoptimized + debuginfo] target(s) in 0.10s
     Running `target/debug/neovide`
Ignored client type property: "methods"
Ignored client type property: "attributes"
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: CreationErrors([NotSupported("lacking either libGL or libEGL so could not fallback to other"), NotSupported("both libGL and libEGL are not present")])', src/window/glutin/mod.rs:418:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by Kethku** [comment]
I'm going to be honest, I know nothing about linux graphics libraries/infrastructure, so I'm not sure how much help I will be.

How bout another tact, maybe I can copy the graphics systems from alacritty. Do you know, do you run into similar problems running it? They use glutin to get a graphics context so maybe I can emulate their strategy.

**Comment by Kethku** [comment]
https://github.com/alacritty/alacritty/issues/3867

This seems to indicate there are extra steps necessary. I guess you need to modify the "rpath" (I have no idea what that means) using a tool called patchelf. Maybe this can unblock you?

**Comment by teto** [comment]
the patchelf solution does bring me further apparently. Still failing though
```
target/debug/neovide
Ignored client type property: "methods"
Ignored client type property: "attributes"
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: CreationErrors([NoAvailablePixelFormat, Window(OsError { line: 430, file: "/home/teto/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.24.0/src/platform_impl/linux/x11/window.rs", error: XError(XError { description: "BadWindow (invalid Window parameter)", error_code: 3, request_code: 3, minor_code: 0 }) })])', src/window/glutin/mod.rs:418:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by Kethku** [comment]
Very interesting. Any chance you were able to try that same thing with alacritty? If it works there I can copy their window create logic and hopefully get you running with neovide.

**Comment by teto** [comment]
alacritty works fine.

**Comment by Kethku** [comment]
Ok. I will dig in. Gimme a bit

**Comment by Kethku** [comment]
At this point I am confident that the opengl port will become the main branch because I think it unblocks a lot of people with basically no down sides. I appreciate you sticking with it and helping me debug this stuff as I only have a windows box. Thanks

**Comment by teto** [comment]
Likewise, thanks for the help I know it's tough to support the various systems. I wish we could see fancier neovim GUIs (oni had the potential but oni2 doesn't use neovim anymore) so if we can fix some of the bugs pestering UIs I am all in. It's also the opportunity to dabble in rust a bit :)

**Comment by Kethku** [comment]
I made some changes to the way neovide constructs the window in main. Could you try again? I'm getting reports it still doesn't work, but it may give me some more hints about what needs work next.

**Comment by Kethku** [comment]
@teto could you give some details as to how you fixed the font config issue?

**Comment by j4qfrost** [comment]
@teto @Kethku I made some progress with the snap install. I think I might have something working this weekend. Have you tried running ```fc-cache -vf``` in the nix package?

**Comment by GabrielGCardoso** [comment]
I have the same bug about fonts, I installed by [debian/ubuntu](https://github.com/teto/neovide/tree/nix#debianubuntu) steps on my Ubuntu 20.04
![Screenshot from 2021-05-12 23-19-19](https://user-images.githubusercontent.com/21351737/118068345-94461380-b378-11eb-992e-f7537cc4e09a.png)

**Comment by zubairakram** [comment]
same error

**Comment by domogami** [comment]
I am having a very similar issue on Arch and I am not sure what to do. I have been messing around with different installs and adding fonts for hours and I might give up for now.

`WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement
Ignored client type property: "methods"
Ignored client type property: "attributes"
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: CreationErrors([NotSupported("lacking either libGL or libEGL so could not fallback to other"), NotSupported("both libGL and libEGL are not present")])', src/window/window_wrapper/mod.rs:429:10`

**Comment by teto** [comment]
fixed on master

**Comment by adrianoviana87** [comment]
If the fix is on master, could the snap version be updated? I'm having the same error `both libGL and libEGL are not present on the snap from the beta channel. I'm on Fedora 34.

**Comment by j4qfrost** [comment]
Try the stable channel. I need to organize the snap releases a bit
differently. Will work on a release workflow on the weekend.
